[tool.poetry]
name = "fastpi-with-django-orm"
version = "0.1.0"
description = "A PoC of using FastAPI alongside Django's ORM"
authors = ["firminoneto11 <firminoneto11@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.*"
django = "4.2.*"
fastapi = "0.104.*"
environs = "9.5.*"
uvicorn = "0.23.*"
uvloop = "0.19.*"
httptools = "0.6.*"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.3"

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
extend-select = ["E501"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
