# Generated by Django 5.1.1 on 2024-09-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0002_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
    ]
