# Generated by Django 5.1.1 on 2024-09-18 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0003_alter_product_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("-pk_id",),
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
